DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "subscriptions" CASCADE;
DROP TABLE IF EXISTS "plan_catalog" CASCADE;
DROP TABLE IF EXISTS "organizations" CASCADE;
DROP TABLE IF EXISTS "open_items" CASCADE;
DROP TABLE IF EXISTS "memberships" CASCADE;
DROP TABLE IF EXISTS "license_keys" CASCADE;
DROP TABLE IF EXISTS "journal_lines" CASCADE;
DROP TABLE IF EXISTS "journal_entries" CASCADE;
DROP TABLE IF EXISTS "invites" CASCADE;
DROP TABLE IF EXISTS "fixed_assets" CASCADE;
DROP TABLE IF EXISTS "fiscal_periods" CASCADE;
DROP TABLE IF EXISTS "documents" CASCADE;
DROP TABLE IF EXISTS "document_sequences" CASCADE;
DROP TABLE IF EXISTS "depreciation_runs" CASCADE;
DROP TABLE IF EXISTS "contacts" CASCADE;
DROP TABLE IF EXISTS "billing_events" CASCADE;
DROP TABLE IF EXISTS "audit_logs" CASCADE;
DROP TABLE IF EXISTS "app_settings" CASCADE;
DROP TABLE IF EXISTS "accounts" CASCADE;

DROP TYPE IF EXISTS "public"."subscription_status";
DROP TYPE IF EXISTS "public"."open_item_type";
DROP TYPE IF EXISTS "public"."open_item_status";
DROP TYPE IF EXISTS "public"."membership_role";
DROP TYPE IF EXISTS "public"."journal_status";
DROP TYPE IF EXISTS "public"."invite_status";
DROP TYPE IF EXISTS "public"."document_type";
DROP TYPE IF EXISTS "public"."document_status";
DROP TYPE IF EXISTS "public"."billing_event_type";
DROP TYPE IF EXISTS "public"."account_type";
